export enum QueryKey {
  USER = 'users',
  TRADIE = 'tradies',
  ORDER = 'orders',
  REPORT = 'report',
  OPEN_ORDER = 'open_orders',
  SHIPPED_ORDER = 'shipped_orders',
  CLOSED_ORDER = 'closed_orders',
  PRODUCT_ALL = 'products-all',
  PRODUCTS = 'products',
  ORDER_ISSUES = 'order_issues',
  ORDER_ISSUE_STATUSES = 'order_issues_statuses',
  PRODUCT_REPORT = 'product_report',
  ORDER_COUNT = 'order-count',
  SELECT_ADDRESSES = 'select-addresses',
  SELECT_CUSTOMER = 'select-customer',
  SELECT_USER = 'select-user',
  PAYMENTS = 'payments-all',
  FULL_SEARCH = 'full_search',
  ORDER_COLUMN_ORDER = 'order_column_order',
  ORDER_DOCUMENT_TEMPLATE = 'order_document_template',
  TAG = 'tag',
  SHIPMENT_METADATA = 'shipment_metadata',
  TAG_ALL = 'tag-all',

  GENERATE_MANUAL_REPORT = 'generate-manual-report',
  AUTOMATION_RULES = 'automation-rules',
  AUTOMATION_RULES_SCHEMA = 'automation-rules-schema',
  SHIPMENT_BATCH = 'shipment_batch',
}
